// <auto-generated />
namespace EfDemo160418_2.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Addedeyes : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Addedeyes));
        
        string IMigrationMetadata.Id
        {
            get { return "201604181221558_Added eyes"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
